# Generated by Django 3.0 on 2021-02-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountname',
            name='type_of_acc',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='acc_head',
        ),
        migrations.RemoveField(
            model_name='journallogdetail',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='journallogdetail',
            name='journal_log',
        ),
        migrations.DeleteModel(
            name='AccountHead',
        ),
        migrations.DeleteModel(
            name='AccountName',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='JournalLog',
        ),
        migrations.DeleteModel(
            name='JournalLogDetail',
        ),
    ]
