# Generated by Django 3.0 on 2021-02-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc_info', '0002_auto_20210226_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccountName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=100)),
                ('opening_balance', models.FloatField()),
                ('closing_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JournalLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_info.AccountName')),
                ('journal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_info.JournalLog')),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type_name', models.CharField(max_length=100)),
                ('acc_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_info.AccountHead')),
            ],
        ),
        migrations.AddField(
            model_name='accountname',
            name='type_of_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_info.AccountType'),
        ),
    ]
